language: python
python:
  - "3.8"
dist: bionic     # https://docs.travis-ci.com/user/languages/python/#python-37-and-higher
install:
  - travis_retry pip install -U -r doc/requirements.txt
  - travis_retry pip install -e .
after_success:
  - make -C doc html
branches:
  only:
    - main
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  on:
    branch: main
  local_dir: doc/build/html
